//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resGlobal_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resGlobal_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Global.resGlobal_TH", typeof(resGlobal_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกี่ยวกับ.
        /// </summary>
        internal static string tAbout {
            get {
                return ResourceManager.GetString("tAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่1.
        /// </summary>
        internal static string tAddr1 {
            get {
                return ResourceManager.GetString("tAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่2.
        /// </summary>
        internal static string tAddr2 {
            get {
                return ResourceManager.GetString("tAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่า.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        internal static string tBack {
            get {
                return ResourceManager.GetString("tBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบส่งเงิน.
        /// </summary>
        internal static string tBanknote {
            get {
                return ResourceManager.GetString("tBanknote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาร์โค้ด.
        /// </summary>
        internal static string tBarcode {
            get {
                return ResourceManager.GetString("tBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องคิดเลข.
        /// </summary>
        internal static string tCalculate {
            get {
                return ResourceManager.GetString("tCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกบิล.
        /// </summary>
        internal static string tCancelBill {
            get {
                return ResourceManager.GetString("tCancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้ราคาเดิม.
        /// </summary>
        internal static string tCancelNewPri {
            get {
                return ResourceManager.GetString("tCancelNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกเติมเงิน.
        /// </summary>
        internal static string tCancelTopup {
            get {
                return ResourceManager.GetString("tCancelTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทบัตร.
        /// </summary>
        internal static string tCardType {
            get {
                return ResourceManager.GetString("tCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงานขาย.
        /// </summary>
        internal static string tCashier {
            get {
                return ResourceManager.GetString("tCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินทอน.
        /// </summary>
        internal static string tChange {
            get {
                return ResourceManager.GetString("tChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชาร์จ.
        /// </summary>
        internal static string tChg {
            get {
                return ResourceManager.GetString("tChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัส.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันใช้ราคาใหม่.
        /// </summary>
        internal static string tConfirmNewPri {
            get {
                return ResourceManager.GetString("tConfirmNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนา.
        /// </summary>
        internal static string tCopy {
            get {
                return ResourceManager.GetString("tCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คูปอง.
        /// </summary>
        internal static string tCoupon {
            get {
                return ResourceManager.GetString("tCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คูปองส่วนลด.
        /// </summary>
        internal static string tCpnDis {
            get {
                return ResourceManager.GetString("tCpnDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คูปองแลกซื้อ.
        /// </summary>
        internal static string tCpnRd {
            get {
                return ResourceManager.GetString("tCpnRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่า.
        /// </summary>
        internal static string tCS_Amt {
            get {
                return ResourceManager.GetString("tCS_Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! พักบิล !!!.
        /// </summary>
        internal static string tCS_HoldBill {
            get {
                return ResourceManager.GetString("tCS_HoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการชำระ.
        /// </summary>
        internal static string tCS_RcvType {
            get {
                return ResourceManager.GetString("tCS_RcvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับ.
        /// </summary>
        internal static string tCS_Receiver {
            get {
                return ResourceManager.GetString("tCS_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ส่ง.
        /// </summary>
        internal static string tCS_Sender {
            get {
                return ResourceManager.GetString("tCS_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string tCS_Seq {
            get {
                return ResourceManager.GetString("tCS_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบส่งเงิน.
        /// </summary>
        internal static string tCS_ShiftBNK {
            get {
                return ResourceManager.GetString("tCS_ShiftBNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก สรุปยอดเงิน.
        /// </summary>
        internal static string tCS_ShiftRcv {
            get {
                return ResourceManager.GetString("tCS_ShiftRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! ปิดการขาย !!!.
        /// </summary>
        internal static string tCS_ShiftSUM {
            get {
                return ResourceManager.GetString("tCS_ShiftSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวมทั้งหมด.
        /// </summary>
        internal static string tCS_TotalAmt {
            get {
                return ResourceManager.GetString("tCS_TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! ยกเลิกบิล !!!.
        /// </summary>
        internal static string tCS_VoidBill {
            get {
                return ResourceManager.GetString("tCS_VoidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเครดิต.
        /// </summary>
        internal static string tCstCredit {
            get {
                return ResourceManager.GetString("tCstCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สกุลเงิน.
        /// </summary>
        internal static string tCurrency {
            get {
                return ResourceManager.GetString("tCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันและเวลา.
        /// </summary>
        internal static string tDatetime {
            get {
                return ResourceManager.GetString("tDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        internal static string tDel {
            get {
                return ResourceManager.GetString("tDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        internal static string tDetail {
            get {
                return ResourceManager.GetString("tDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลด.
        /// </summary>
        internal static string tDis {
            get {
                return ResourceManager.GetString("tDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสาร.
        /// </summary>
        internal static string tDoc {
            get {
                return ResourceManager.GetString("tDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขเอกสาร.
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลด.
        /// </summary>
        internal static string tDownload {
            get {
                return ResourceManager.GetString("tDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        internal static string tExit {
            get {
                return ResourceManager.GetString("tExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tExpire {
            get {
                return ResourceManager.GetString("tExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนหน่วย.
        /// </summary>
        internal static string tFactor {
            get {
                return ResourceManager.GetString("tFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่นชอบ.
        /// </summary>
        internal static string tFavorite {
            get {
                return ResourceManager.GetString("tFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แฟกซ์.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรองข้อมูล.
        /// </summary>
        internal static string tFilter {
            get {
                return ResourceManager.GetString("tFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความถี่.
        /// </summary>
        internal static string tFreq {
            get {
                return ResourceManager.GetString("tFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟังก์ชันการประมวลผลผิดพลาด.
        /// </summary>
        internal static string tFuncError {
            get {
                return ResourceManager.GetString("tFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่นที่ได้รับ.
        /// </summary>
        internal static string tGetPromotion {
            get {
                return ResourceManager.GetString("tGetPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มลูกค้า.
        /// </summary>
        internal static string tGrpCst {
            get {
                return ResourceManager.GetString("tGrpCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วยเหลือ.
        /// </summary>
        internal static string tHelp {
            get {
                return ResourceManager.GetString("tHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พักบิล.
        /// </summary>
        internal static string tHoldBill {
            get {
                return ResourceManager.GetString("tHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คีบอร์ด.
        /// </summary>
        internal static string tKeyboard {
            get {
                return ResourceManager.GetString("tKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล็อคหน้าจอ.
        /// </summary>
        internal static string tLockKb {
            get {
                return ResourceManager.GetString("tLockKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเงินเข้า.
        /// </summary>
        internal static string tMnyIn {
            get {
                return ResourceManager.GetString("tMnyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเงินออก.
        /// </summary>
        internal static string tMnyOut {
            get {
                return ResourceManager.GetString("tMnyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่อง.
        /// </summary>
        internal static string tMsg_Col {
            get {
                return ResourceManager.GetString("tMsg_Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า.
        /// </summary>
        internal static string tMsg_Pdt {
            get {
                return ResourceManager.GetString("tMsg_Pdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องจุดขาย.
        /// </summary>
        internal static string tMsg_Pos {
            get {
                return ResourceManager.GetString("tMsg_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tMsg_Qty {
            get {
                return ResourceManager.GetString("tMsg_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แถว.
        /// </summary>
        internal static string tMsg_Row {
            get {
                return ResourceManager.GetString("tMsg_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกจำนวนเงินมากกว่า 0 .
        /// </summary>
        internal static string tMsgAmountZero {
            get {
                return ResourceManager.GetString("tMsgAmountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถสร้างเอกสารได้.
        /// </summary>
        internal static string tMsgCannotCreateDoc {
            get {
                return ResourceManager.GetString("tMsgCannotCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีสิทธิใช้งาน.
        /// </summary>
        internal static string tMsgCannotOpen {
            get {
                return ResourceManager.GetString("tMsgCannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถกลับสู่เมนูหลักได้.
        /// </summary>
        internal static string tMsgCantBack {
            get {
                return ResourceManager.GetString("tMsgCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถติดต่อเว็บเซอร์วิสได้.
        /// </summary>
        internal static string tMsgCantService {
            get {
                return ResourceManager.GetString("tMsgCantService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินทอนมีค่าเกินกว่า {0} กรุณาใส่ใหม่.
        /// </summary>
        internal static string tMsgChgOver {
            get {
                return ResourceManager.GetString("tMsgChgOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถปิดรอบการขายได้ เนื่องจากมีรายการพักบิลค้างอยู่ !!!   ต้องการลบรายการพักบิล หรือไม่ ?.
        /// </summary>
        internal static string tMsgChkHoldBill {
            get {
                return ResourceManager.GetString("tMsgChkHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดปุ่มตรวจบัตรเพื่อตรวจสอบหมายเลขบัตร.
        /// </summary>
        internal static string tMsgClickAccept {
            get {
                return ResourceManager.GetString("tMsgClickAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เชื่อมต่อ URL สำเร็จ.
        /// </summary>
        internal static string tMsgConnUrlSuccess {
            get {
                return ResourceManager.GetString("tMsgConnUrlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล !!!.
        /// </summary>
        internal static string tMsgDataNotFound {
            get {
                return ResourceManager.GetString("tMsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินส่วนลด เกินกว่าจำนวนเงินรวม ที่สามารถลดได้.
        /// </summary>
        internal static string tMsgDisOver {
            get {
                return ResourceManager.GetString("tMsgDisOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่ออินเตอร์เน็ตได้ กรุณาตรวจสอบ.
        /// </summary>
        internal static string tMsgErrCon {
            get {
                return ResourceManager.GetString("tMsgErrCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการออกจากระบบหรือไม่?.
        /// </summary>
        internal static string tMsgExit {
            get {
                return ResourceManager.GetString("tMsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการชำระเงินไปแล้วบางส่วน ไม่สามารถทำการลด/ชาร์จได้อีก.
        /// </summary>
        internal static string tMsgFirstPay {
            get {
                return ResourceManager.GetString("tMsgFirstPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีรายการขายบางส่วนคงค้างอยู่ จึงไม่สามารถทำงานฟังก์ชันนี้ได้.
        /// </summary>
        internal static string tMsgHaveItem {
            get {
                return ResourceManager.GetString("tMsgHaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการพักรายการปัจจุบัน หรือไม่?.
        /// </summary>
        internal static string tMsgHoldBill {
            get {
                return ResourceManager.GetString("tMsgHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกจำนวนเงิน.
        /// </summary>
        internal static string tMsgInputAmount {
            get {
                return ResourceManager.GetString("tMsgInputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อผู้ใช้และรหัสผ่าน.
        /// </summary>
        internal static string tMsgInputUsrPwd {
            get {
                return ResourceManager.GetString("tMsgInputUsrPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขริชแบนด์ / บัตร.
        /// </summary>
        internal static string tMsgInputWristband {
            get {
                return ResourceManager.GetString("tMsgInputWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบวันที่ไม่ถูกต้อง.
        /// </summary>
        internal static string tMsgInvalidDate {
            get {
                return ResourceManager.GetString("tMsgInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้และรหัสผ่านผิด.
        /// </summary>
        internal static string tMsgInvalidUsr {
            get {
                return ResourceManager.GetString("tMsgInvalidUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้ผิด.
        /// </summary>
        internal static string tMsgInvalidUsrname {
            get {
                return ResourceManager.GetString("tMsgInvalidUsrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลาในการเปิดรอบ ต้องอยู่ในช่วง 1 ปีของปัจจุบัน.
        /// </summary>
        internal static string tMsgLongTime {
            get {
                return ResourceManager.GetString("tMsgLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล เพื่อที่จะทำรายการได้.
        /// </summary>
        internal static string tMsgNoData {
            get {
                return ResourceManager.GetString("tMsgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล เพื่อที่จะทำรายการได้.
        /// </summary>
        internal static string tMsgNoItem {
            get {
                return ResourceManager.GetString("tMsgNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีที่อยู่ของเว็บเซอร์วิส กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        internal static string tMsgNoService {
            get {
                return ResourceManager.GetString("tMsgNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลดเอกสารหลังการชาร์จท้ายบิลได้.
        /// </summary>
        internal static string tMsgNotAlwDisAftChg {
            get {
                return ResourceManager.GetString("tMsgNotAlwDisAftChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลูกค้าท่านนี้ไม่ได้รับอนุญาตให้ใช้คะแนน !!!.
        /// </summary>
        internal static string tMsgNotAlwRedeem {
            get {
                return ResourceManager.GetString("tMsgNotAlwRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถย้อนกลับไปหน้าขายได้ เนื่องจากมีการยืนยันใช้ราคาใหม่แล้ว.
        /// </summary>
        internal static string tMsgNotBackSale {
            get {
                return ResourceManager.GetString("tMsgNotBackSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้เลือกลูกค้า.
        /// </summary>
        internal static string tMsgNotChooseCst {
            get {
                return ResourceManager.GetString("tMsgNotChooseCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อ URL ได้.
        /// </summary>
        internal static string tMsgNotConnUrl {
            get {
                return ResourceManager.GetString("tMsgNotConnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบหมายเลขริสแบนด์ / บัตร : {0}.
        /// </summary>
        internal static string tMsgNotfoundCard {
            get {
                return ResourceManager.GetString("tMsgNotfoundCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการขายได้ เนื่องจากมีรอบการขายของผู้ใช้งานท่านอื่นค้างอยู่ (ผู้ใช้ : {0})
        ///กรุณากด Yes เพื่อปิดรอบการขายก่อนหน้า และเปิดรอบการขายใหม่
        ///กรุณากด No เพื่อให้ผู้ใช้งานที่เปิดรอบค้างไว้ทำการปิดรอบก่อน.
        /// </summary>
        internal static string tMsgOpenShift {
            get {
                return ResourceManager.GetString("tMsgOpenShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดังนั้นคุณต้องการที่จะ รับชำระด้วยยอดทั้งหมดที่เหลือหรือไม่?.
        /// </summary>
        internal static string tMsgPayConfirm {
            get {
                return ResourceManager.GetString("tMsgPayConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินรับ มากกว่ายอดที่ชำระ, ชำระโดยคูปองเงินสด,เช็ค,แลกแต้ม จะไม่มีเงินทอน.
        /// </summary>
        internal static string tMsgPayMost {
            get {
                return ResourceManager.GetString("tMsgPayMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้กำหนดเครื่องจุดขาย !!!.
        /// </summary>
        internal static string tMsgPosNotDefine {
            get {
                return ResourceManager.GetString("tMsgPosNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณา ระบุยอดเงิน.
        /// </summary>
        internal static string tMsgShiftCheck {
            get {
                return ResourceManager.GetString("tMsgShiftCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอบการขายไม่ใช่รอบของวันปัจจุบัน กรุณาปิดรอบการขายเดิมก่อน !!!.
        /// </summary>
        internal static string tMsgShiftDateInvalid {
            get {
                return ResourceManager.GetString("tMsgShiftDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้กำหนด URL API2ARDoc.
        /// </summary>
        internal static string tMsgUrlARDocNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlARDocNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุที่อยู่ของเว็บเซอร์วิสร้านค้า.
        /// </summary>
        internal static string tMsgURLStore {
            get {
                return ResourceManager.GetString("tMsgURLStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้กำหนด URL API2FNWallet.
        /// </summary>
        internal static string tMsgUrlWalletNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlWalletNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการยกเลิกบิลใช่หรือไม่.
        /// </summary>
        internal static string tMsgVoidBill {
            get {
                return ResourceManager.GetString("tMsgVoidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *เมื่อยืนยันใช้ราคาใหม่ ระบบจะเคลียร์ส่วนลด/ชาร์จรายการออกทั้งหมด.
        /// </summary>
        internal static string tMsgWarnigClear {
            get {
                return ResourceManager.GetString("tMsgWarnigClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยินดีต้อนรับกลับ เข้าสู่การทำงาน.
        /// </summary>
        internal static string tMsgWelcome {
            get {
                return ResourceManager.GetString("tMsgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาใหม่.
        /// </summary>
        internal static string tNewPrice {
            get {
                return ResourceManager.GetString("tNewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มียอดที่สามารถทำรายการ ลด/ชาร์จ ได้.
        /// </summary>
        internal static string tNoAmtDisChg {
            get {
                return ResourceManager.GetString("tNoAmtDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดลิ้นชักไม่ขาย.
        /// </summary>
        internal static string tOpDrwNoS {
            get {
                return ResourceManager.GetString("tOpDrwNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาเดิม.
        /// </summary>
        internal static string tOriPrice {
            get {
                return ResourceManager.GetString("tOriPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุญาตสิทธิ์ใช้งานบนหน้าจอ .
        /// </summary>
        internal static string tOverride {
            get {
                return ResourceManager.GetString("tOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบ {0} ข้อมูล. หน้า {1} / {2}.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้า {0} / {1}.
        /// </summary>
        internal static string tPagePay {
            get {
                return ResourceManager.GetString("tPagePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บางส่วนของข้อความ.
        /// </summary>
        internal static string tPartField {
            get {
                return ResourceManager.GetString("tPartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        internal static string tPassword {
            get {
                return ResourceManager.GetString("tPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมเงิน.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        internal static string tPdtCode {
            get {
                return ResourceManager.GetString("tPdtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการจัดสินค้ารายการนี้ เป็นสินค้าฟรีหรือไม่?.
        /// </summary>
        internal static string tPdtFree {
            get {
                return ResourceManager.GetString("tPdtFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปยอดขายสินค้าควบคุมพิเศษ.
        /// </summary>
        internal static string tPdtSpcSum {
            get {
                return ResourceManager.GetString("tPdtSpcSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบหยิบสินค้า.
        /// </summary>
        internal static string tPickinglist {
            get {
                return ResourceManager.GetString("tPickinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คะแนน.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขเครื่อง.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวอย่างก่อนพิมพ์.
        /// </summary>
        internal static string tPreview {
            get {
                return ResourceManager.GetString("tPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์.
        /// </summary>
        internal static string tPrint {
            get {
                return ResourceManager.GetString("tPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์วันที่.
        /// </summary>
        internal static string tPrintDate {
            get {
                return ResourceManager.GetString("tPrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์.
        /// </summary>
        internal static string tPrivilege {
            get {
                return ResourceManager.GetString("tPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสำเร็จรูป.
        /// </summary>
        internal static string tQuickAmt {
            get {
                return ResourceManager.GetString("tQuickAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แลกแต้มรับส่วนลด.
        /// </summary>
        internal static string tRdDis {
            get {
                return ResourceManager.GetString("tRdDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แลกแต้มรับสินค้า.
        /// </summary>
        internal static string tRdPdt {
            get {
                return ResourceManager.GetString("tRdPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เหตุผล.
        /// </summary>
        internal static string tReason {
            get {
                return ResourceManager.GetString("tReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับ.
        /// </summary>
        internal static string tReceiver {
            get {
                return ResourceManager.GetString("tReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่นแนะนำ.
        /// </summary>
        internal static string tRecomed {
            get {
                return ResourceManager.GetString("tRecomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างอิงเลขที่.
        /// </summary>
        internal static string tRefer {
            get {
                return ResourceManager.GetString("tRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคืน.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคืนสินค้า.
        /// </summary>
        internal static string tRefundAmt {
            get {
                return ResourceManager.GetString("tRefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลคืน จาก.
        /// </summary>
        internal static string tRefundFrm {
            get {
                return ResourceManager.GetString("tRefundFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! คืนสินค้า !.
        /// </summary>
        internal static string tRefundPdt {
            get {
                return ResourceManager.GetString("tRefundPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลคืน ถึง.
        /// </summary>
        internal static string tRefundTo {
            get {
                return ResourceManager.GetString("tRefundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขาย.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขาย.
        /// </summary>
        internal static string tSaleAmt {
            get {
                return ResourceManager.GetString("tSaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขาย.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลขาย จาก.
        /// </summary>
        internal static string tSaleFrm {
            get {
                return ResourceManager.GetString("tSaleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานสรุปยอดขาย.
        /// </summary>
        internal static string tSaleSumRpt {
            get {
                return ResourceManager.GetString("tSaleSumRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลขาย ถึง.
        /// </summary>
        internal static string tSaleTo {
            get {
                return ResourceManager.GetString("tSaleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาโดย.
        /// </summary>
        internal static string tSchBy {
            get {
                return ResourceManager.GetString("tSchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาเอกสาร.
        /// </summary>
        internal static string tSchDoc {
            get {
                return ResourceManager.GetString("tSchDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ส่ง.
        /// </summary>
        internal static string tSender {
            get {
                return ResourceManager.GetString("tSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string tSeq {
            get {
                return ResourceManager.GetString("tSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่รอบ.
        /// </summary>
        internal static string tShiftCode {
            get {
                return ResourceManager.GetString("tShiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟังก์ชั่นคีบอร์ด.
        /// </summary>
        internal static string tShowKb {
            get {
                return ResourceManager.GetString("tShowKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปยอดเงินสดทั้งหมด.
        /// </summary>
        internal static string tSumCash {
            get {
                return ResourceManager.GetString("tSumCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปการรับชำระเงิน(สกุลเงิน).
        /// </summary>
        internal static string tSumCurrency {
            get {
                return ResourceManager.GetString("tSumCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        internal static string tSummary {
            get {
                return ResourceManager.GetString("tSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำผู้ตัวเสียภาษี.
        /// </summary>
        internal static string tTaxID {
            get {
                return ResourceManager.GetString("tTaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบกำกับภาษีอย่างย่อ.
        /// </summary>
        internal static string tTaxInvoice {
            get {
                return ResourceManager.GetString("tTaxInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั๋ว.
        /// </summary>
        internal static string tTicket {
            get {
                return ResourceManager.GetString("tTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข URL.
        /// </summary>
        internal static string tTitleEdit {
            get {
                return ResourceManager.GetString("tTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string tTitleURL {
            get {
                return ResourceManager.GetString("tTitleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เติมเงิน.
        /// </summary>
        internal static string tTopup {
            get {
                return ResourceManager.GetString("tTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมเงิน.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมราคาใหม่.
        /// </summary>
        internal static string tTotalNewPri {
            get {
                return ResourceManager.GetString("tTotalNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมราคาเดิม.
        /// </summary>
        internal static string tTotalOldPri {
            get {
                return ResourceManager.GetString("tTotalOldPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อหน่วย.
        /// </summary>
        internal static string tUnitName {
            get {
                return ResourceManager.GetString("tUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string tUsername {
            get {
                return ResourceManager.GetString("tUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ใช้.
        /// </summary>
        internal static string tUsr {
            get {
                return ResourceManager.GetString("tUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษีแยกนอก.
        /// </summary>
        internal static string tVatExcluded {
            get {
                return ResourceManager.GetString("tVatExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษีรวมใน.
        /// </summary>
        internal static string tVatIncluded {
            get {
                return ResourceManager.GetString("tVatIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยินดีต้อนรับ.
        /// </summary>
        internal static string tWelcome {
            get {
                return ResourceManager.GetString("tWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมดของข้อความ.
        /// </summary>
        internal static string tWholeField {
            get {
                return ResourceManager.GetString("tWholeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ริชแบนด์.
        /// </summary>
        internal static string tWristband {
            get {
                return ResourceManager.GetString("tWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขริชแบนด์ / บัตร.
        /// </summary>
        internal static string tWristbandNo {
            get {
                return ResourceManager.GetString("tWristbandNo", resourceCulture);
            }
        }
    }
}
