//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2Wallet.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdaFCEntities : DbContext
    {
        /// <summary>
        /// 
        /// </summary>
        public AdaFCEntities()
            : base("name=AdaFCEntities")
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ptConnStr"></param>
        public AdaFCEntities(string ptConnStr) : base(ptConnStr)
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    }
}
