//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resPopup_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resPopup_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resPopup_EN", typeof(resPopup_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tAbout {
            get {
                return ResourceManager.GetString("tAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string tAdd {
            get {
                return ResourceManager.GetString("tAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tAmt {
            get {
                return ResourceManager.GetString("tAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string tBchCode {
            get {
                return ResourceManager.GetString("tBchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color More ... .
        /// </summary>
        internal static string tButtonSetColor {
            get {
                return ResourceManager.GetString("tButtonSetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Coupon.
        /// </summary>
        internal static string tCashCoupon {
            get {
                return ResourceManager.GetString("tCashCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string tChange {
            get {
                return ResourceManager.GetString("tChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Date.
        /// </summary>
        internal static string tChequeDate {
            get {
                return ResourceManager.GetString("tChequeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        internal static string tChequeNo {
            get {
                return ResourceManager.GetString("tChequeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm PIN Code.
        /// </summary>
        internal static string tChgPINConfirm {
            get {
                return ResourceManager.GetString("tChgPINConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PIN Code.
        /// </summary>
        internal static string tChgPINNew {
            get {
                return ResourceManager.GetString("tChgPINNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old PIN Code.
        /// </summary>
        internal static string tChgPINOld {
            get {
                return ResourceManager.GetString("tChgPINOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string tChgPwdConfirm {
            get {
                return ResourceManager.GetString("tChgPwdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string tChgPwdNew {
            get {
                return ResourceManager.GetString("tChgPwdNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string tChgPwdOld {
            get {
                return ResourceManager.GetString("tChgPwdOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string tChoose {
            get {
                return ResourceManager.GetString("tChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        internal static string tColCstCardID {
            get {
                return ResourceManager.GetString("tColCstCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        internal static string tColCstCode {
            get {
                return ResourceManager.GetString("tColCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Card No..
        /// </summary>
        internal static string tColCstMemCrdNo {
            get {
                return ResourceManager.GetString("tColCstMemCrdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tColCstName {
            get {
                return ResourceManager.GetString("tColCstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No..
        /// </summary>
        internal static string tColCstTaxNo {
            get {
                return ResourceManager.GetString("tColCstTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        internal static string tColCstTel {
            get {
                return ResourceManager.GetString("tColCstTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon No.
        /// </summary>
        internal static string tCouponNo {
            get {
                return ResourceManager.GetString("tCouponNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Value.
        /// </summary>
        internal static string tCpnValue {
            get {
                return ResourceManager.GetString("tCpnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current amount.
        /// </summary>
        internal static string tCurAmt {
            get {
                return ResourceManager.GetString("tCurAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Deposit !!!.
        /// </summary>
        internal static string tDepositHeader {
            get {
                return ResourceManager.GetString("tDepositHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Now.
        /// </summary>
        internal static string tDepositNow {
            get {
                return ResourceManager.GetString("tDepositNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string tDetail {
            get {
                return ResourceManager.GetString("tDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string tDisAmt {
            get {
                return ResourceManager.GetString("tDisAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount conditions.
        /// </summary>
        internal static string tDiscCond {
            get {
                return ResourceManager.GetString("tDiscCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Coupon.
        /// </summary>
        internal static string tDiscountCoupon {
            get {
                return ResourceManager.GetString("tDiscountCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent.
        /// </summary>
        internal static string tDisPer {
            get {
                return ResourceManager.GetString("tDisPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string tEditQtyRfn {
            get {
                return ResourceManager.GetString("tEditQtyRfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sale Price.
        /// </summary>
        internal static string tEditSalePrice {
            get {
                return ResourceManager.GetString("tEditSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frq.
        /// </summary>
        internal static string tFrq {
            get {
                return ResourceManager.GetString("tFrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Scan.
        /// </summary>
        internal static string tKeyScan {
            get {
                return ResourceManager.GetString("tKeyScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string tLanguage {
            get {
                return ResourceManager.GetString("tLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Quantity.
        /// </summary>
        internal static string tLimitQty {
            get {
                return ResourceManager.GetString("tLimitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest user is.
        /// </summary>
        internal static string tLocSplashLastUser {
            get {
                return ResourceManager.GetString("tLocSplashLastUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log out?.
        /// </summary>
        internal static string tLocSplasMsghigh {
            get {
                return ResourceManager.GetString("tLocSplasMsghigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no rights to unlock!.
        /// </summary>
        internal static string tLocSplasMsgLow {
            get {
                return ResourceManager.GetString("tLocSplasMsgLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill made an automatic return Alipay. Because  Alipay problem before contact.Please advise customers to check Alipay balance..
        /// </summary>
        internal static string tMsgAlipayAutoVoid {
            get {
                return ResourceManager.GetString("tMsgAlipayAutoVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill can not be paid by Alipay. Please pay by others..
        /// </summary>
        internal static string tMsgAliPayNotPay {
            get {
                return ResourceManager.GetString("tMsgAliPayNotPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem contact with alipay.Please advise customers to check Alipay balance..
        /// </summary>
        internal static string tMsgAlipayProblem {
            get {
                return ResourceManager.GetString("tMsgAlipayProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not select new customers if there are some items on the bil.
        /// </summary>
        internal static string tMsgCantSelectCst {
            get {
                return ResourceManager.GetString("tMsgCantSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        internal static string tMsgChgPwdIncorrect {
            get {
                return ResourceManager.GetString("tMsgChgPwdIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be the same as the {1}.
        /// </summary>
        internal static string tMsgChgPwdNewSameOld {
            get {
                return ResourceManager.GetString("tMsgChgPwdNewSameOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        internal static string tMsgChgPwdReqPram {
            get {
                return ResourceManager.GetString("tMsgChgPwdReqPram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Success..
        /// </summary>
        internal static string tMsgChgPwdSuccess {
            get {
                return ResourceManager.GetString("tMsgChgPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check report file.
        /// </summary>
        internal static string tMsgChkReport {
            get {
                return ResourceManager.GetString("tMsgChkReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose reason.
        /// </summary>
        internal static string tMsgChooseReason {
            get {
                return ResourceManager.GetString("tMsgChooseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is exceed per Bill.
        /// </summary>
        internal static string tMsgCpnLimitPerBill {
            get {
                return ResourceManager.GetString("tMsgCpnLimitPerBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose customer information..
        /// </summary>
        internal static string tMsgCstSchChoose {
            get {
                return ResourceManager.GetString("tMsgCstSchChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter information for searching..
        /// </summary>
        internal static string tMsgCstSchReq {
            get {
                return ResourceManager.GetString("tMsgCstSchReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open shift because date for open less than date used to open.
        /// </summary>
        internal static string tMsgDateOpenAgain {
            get {
                return ResourceManager.GetString("tMsgDateOpenAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference price level cannot change (just change by cancel document).
        /// </summary>
        internal static string tMsgDiffPriLev {
            get {
                return ResourceManager.GetString("tMsgDiffPriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of edit must than 0 !!!.
        /// </summary>
        internal static string tMsgEditQtyFale {
            get {
                return ResourceManager.GetString("tMsgEditQtyFale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price will below than specific.
        ///If continue will cancel all discount of this product..
        /// </summary>
        internal static string tMsgEditQtyPriceless {
            get {
                return ResourceManager.GetString("tMsgEditQtyPriceless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Not Success !!!.
        /// </summary>
        internal static string tMsgErrChgPwdUnSuccess {
            get {
                return ResourceManager.GetString("tMsgErrChgPwdUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quantity returned is more than the sales Quantity !!!.
        /// </summary>
        internal static string tMsgErrQtyRfn {
            get {
                return ResourceManager.GetString("tMsgErrQtyRfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Coupon Data not Success.
        /// </summary>
        internal static string tMsgGetCouponNotSuccess {
            get {
                return ResourceManager.GetString("tMsgGetCouponNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Redeen Point Data not Success.
        /// </summary>
        internal static string tMsgGetRedeemNotSuccess {
            get {
                return ResourceManager.GetString("tMsgGetRedeemNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input bank !!!.
        /// </summary>
        internal static string tMsgInputBank {
            get {
                return ResourceManager.GetString("tMsgInputBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input coupon no.
        /// </summary>
        internal static string tMsgInputCoupon {
            get {
                return ResourceManager.GetString("tMsgInputCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input deposit.
        /// </summary>
        internal static string tMsgInputDeposit {
            get {
                return ResourceManager.GetString("tMsgInputDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input number !!!.
        /// </summary>
        internal static string tMsgInputNum {
            get {
                return ResourceManager.GetString("tMsgInputNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input withdraw.
        /// </summary>
        internal static string tMsgInputWithdraw {
            get {
                return ResourceManager.GetString("tMsgInputWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to manual key in?.
        /// </summary>
        internal static string tMsgManualKey {
            get {
                return ResourceManager.GetString("tMsgManualKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item is allowed to Dis / Charge.
        /// </summary>
        internal static string tMsgNoItemDisChrg {
            get {
                return ResourceManager.GetString("tMsgNoItemDisChrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon no cannot be found. Or already been used.
        /// </summary>
        internal static string tMsgNoItemOrUsed {
            get {
                return ResourceManager.GetString("tMsgNoItemOrUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use on Top Promotion.
        /// </summary>
        internal static string tMsgNoOnTopPmt {
            get {
                return ResourceManager.GetString("tMsgNoOnTopPmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw has value greater than deposit.
        /// </summary>
        internal static string tMsgNoWithdraw {
            get {
                return ResourceManager.GetString("tMsgNoWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity over limit.
        /// </summary>
        internal static string tMsgOverLimit {
            get {
                return ResourceManager.GetString("tMsgOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough products !!!.
        /// </summary>
        internal static string tMsgPdtQtyDef {
            get {
                return ResourceManager.GetString("tMsgPdtQtyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already registered as {1}.
        /// </summary>
        internal static string tMsgPosRegFalse {
            get {
                return ResourceManager.GetString("tMsgPosRegFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS registration information has been submitted. Please check the registration approval from the administrator..
        /// </summary>
        internal static string tMsgPosRegSuccess {
            get {
                return ResourceManager.GetString("tMsgPosRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process send create Customer Code Fail..
        /// </summary>
        internal static string tMsgPrcCreateCstCode {
            get {
                return ResourceManager.GetString("tMsgPrcCreateCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item discount is not allowed after payment has been made !!!.
        /// </summary>
        internal static string tMsgRdDisAfterPay {
            get {
                return ResourceManager.GetString("tMsgRdDisAfterPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem more than the Limit !!!.
        /// </summary>
        internal static string tMsgRdLimitQty {
            get {
                return ResourceManager.GetString("tMsgRdLimitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Item that can be Redeem !!!.
        /// </summary>
        internal static string tMsgRdNoItem {
            get {
                return ResourceManager.GetString("tMsgRdNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points !!!.
        /// </summary>
        internal static string tMsgRdNotEnoughPoints {
            get {
                return ResourceManager.GetString("tMsgRdNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a New PIN Code of 6 characters..
        /// </summary>
        internal static string tMsgReqLengthPIN {
            get {
                return ResourceManager.GetString("tMsgReqLengthPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a New password of at least 8 characters..
        /// </summary>
        internal static string tMsgReqLengthPwd {
            get {
                return ResourceManager.GetString("tMsgReqLengthPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select coupon type.
        /// </summary>
        internal static string tMsgSelCoupon {
            get {
                return ResourceManager.GetString("tMsgSelCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select printer.
        /// </summary>
        internal static string tMsgSelDriverPrn {
            get {
                return ResourceManager.GetString("tMsgSelDriverPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Product.
        /// </summary>
        internal static string tMsgSelPdt {
            get {
                return ResourceManager.GetString("tMsgSelPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the color code..
        /// </summary>
        internal static string tMsgSetColorEmpty {
            get {
                return ResourceManager.GetString("tMsgSetColorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code format !.
        /// </summary>
        internal static string tMsgSetColorFalse {
            get {
                return ResourceManager.GetString("tMsgSetColorFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift open success, go to home.
        /// </summary>
        internal static string tMsgShiftOpenSuccess {
            get {
                return ResourceManager.GetString("tMsgShiftOpenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...It is working.
        /// </summary>
        internal static string tMsgWorking {
            get {
                return ResourceManager.GetString("tMsgWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price.
        /// </summary>
        internal static string tNewPrice {
            get {
                return ResourceManager.GetString("tNewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Price.
        /// </summary>
        internal static string tOldPrice {
            get {
                return ResourceManager.GetString("tOldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open shift.
        /// </summary>
        internal static string tOpenShift {
            get {
                return ResourceManager.GetString("tOpenShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper A4.
        /// </summary>
        internal static string tPaperA4 {
            get {
                return ResourceManager.GetString("tPaperA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper thermal.
        /// </summary>
        internal static string tPaperThermal {
            get {
                return ResourceManager.GetString("tPaperThermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string tPassword {
            get {
                return ResourceManager.GetString("tPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by credit.
        /// </summary>
        internal static string tPayCrd {
            get {
                return ResourceManager.GetString("tPayCrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by cash.
        /// </summary>
        internal static string tPayCsh {
            get {
                return ResourceManager.GetString("tPayCsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        internal static string tPdtDesc {
            get {
                return ResourceManager.GetString("tPdtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New  Quantity.
        /// </summary>
        internal static string tPdtQtyNew {
            get {
                return ResourceManager.GetString("tPdtQtyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Quantity.
        /// </summary>
        internal static string tPdtQtyOld {
            get {
                return ResourceManager.GetString("tPdtQtyOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin code.
        /// </summary>
        internal static string tPincode {
            get {
                return ResourceManager.GetString("tPincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos Code.
        /// </summary>
        internal static string tPosCode {
            get {
                return ResourceManager.GetString("tPosCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous sum.
        /// </summary>
        internal static string tPreviousSum {
            get {
                return ResourceManager.GetString("tPreviousSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Quantity.
        /// </summary>
        internal static string tQtyRfn {
            get {
                return ResourceManager.GetString("tQtyRfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string tRdColBarcode {
            get {
                return ResourceManager.GetString("tRdColBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string tRdColChoose {
            get {
                return ResourceManager.GetString("tRdColChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum balance.
        /// </summary>
        internal static string tRdColMinTotBill {
            get {
                return ResourceManager.GetString("tRdColMinTotBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tRdColPdtName {
            get {
                return ResourceManager.GetString("tRdColPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string tRdColQty {
            get {
                return ResourceManager.GetString("tRdColQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referent Code.
        /// </summary>
        internal static string tRdColRefCode {
            get {
                return ResourceManager.GetString("tRdColRefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tRdColUnitName {
            get {
                return ResourceManager.GetString("tRdColUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Money.
        /// </summary>
        internal static string tRdColUseMny {
            get {
                return ResourceManager.GetString("tRdColUseMny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Value.
        /// </summary>
        internal static string tRdColUseMnyDis {
            get {
                return ResourceManager.GetString("tRdColUseMnyDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Point.
        /// </summary>
        internal static string tRdColUsePoin {
            get {
                return ResourceManager.GetString("tRdColUsePoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Value.
        /// </summary>
        internal static string tRdColUsePoinDis {
            get {
                return ResourceManager.GetString("tRdColUsePoinDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Coupon.
        /// </summary>
        internal static string tRedeemCoupon {
            get {
                return ResourceManager.GetString("tRedeemCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string tReferSOBchCode {
            get {
                return ResourceManager.GetString("tReferSOBchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        internal static string tReferSOCshOrCrd {
            get {
                return ResourceManager.GetString("tReferSOCshOrCrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string tReferSODate {
            get {
                return ResourceManager.GetString("tReferSODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tReferSODocNo {
            get {
                return ResourceManager.GetString("tReferSODocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Approve.
        /// </summary>
        internal static string tReferSOUsrApv {
            get {
                return ResourceManager.GetString("tReferSOUsrApv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Key.
        /// </summary>
        internal static string tReferSOUsrKey {
            get {
                return ResourceManager.GetString("tReferSOUsrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrive bill.
        /// </summary>
        internal static string tRetriveBill {
            get {
                return ResourceManager.GetString("tRetriveBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Function.
        /// </summary>
        internal static string tRole {
            get {
                return ResourceManager.GetString("tRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale date.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan QR Code.
        /// </summary>
        internal static string tScanQR {
            get {
                return ResourceManager.GetString("tScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string tSelectAll {
            get {
                return ResourceManager.GetString("tSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Color.
        /// </summary>
        internal static string tSetColor {
            get {
                return ResourceManager.GetString("tSetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string tSignin {
            get {
                return ResourceManager.GetString("tSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary amount.
        /// </summary>
        internal static string tSumAmt {
            get {
                return ResourceManager.GetString("tSumAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary frequency.
        /// </summary>
        internal static string tSumFeq {
            get {
                return ResourceManager.GetString("tSumFeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user.
        /// </summary>
        internal static string tSwitch {
            get {
                return ResourceManager.GetString("tSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alipay.
        /// </summary>
        internal static string tTitleAlipay {
            get {
                return ResourceManager.GetString("tTitleAlipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tTitleAmt {
            get {
                return ResourceManager.GetString("tTitleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Code.
        /// </summary>
        internal static string tTitleApvCode {
            get {
                return ResourceManager.GetString("tTitleApvCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string tTitleAuthen {
            get {
                return ResourceManager.GetString("tTitleAuthen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string tTitleAvailable {
            get {
                return ResourceManager.GetString("tTitleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Discount.
        /// </summary>
        internal static string tTitleAvailableDis {
            get {
                return ResourceManager.GetString("tTitleAvailableDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string tTitleBalance {
            get {
                return ResourceManager.GetString("tTitleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string tTitleBank {
            get {
                return ResourceManager.GetString("tTitleBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string tTitleBarCode {
            get {
                return ResourceManager.GetString("tTitleBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string tTitleChangePassword {
            get {
                return ResourceManager.GetString("tTitleChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Quantity.
        /// </summary>
        internal static string tTitleChangePdtQty {
            get {
                return ResourceManager.GetString("tTitleChangePdtQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PIN Code.
        /// </summary>
        internal static string tTitleChangePinCode {
            get {
                return ResourceManager.GetString("tTitleChangePinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Quota.
        /// </summary>
        internal static string tTitleChangeQuota {
            get {
                return ResourceManager.GetString("tTitleChangeQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose coupon.
        /// </summary>
        internal static string tTitleChooseCpn {
            get {
                return ResourceManager.GetString("tTitleChooseCpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Customer.
        /// </summary>
        internal static string tTitleChooseCst {
            get {
                return ResourceManager.GetString("tTitleChooseCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Item.
        /// </summary>
        internal static string tTitleChooseItem {
            get {
                return ResourceManager.GetString("tTitleChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose item for refund.
        /// </summary>
        internal static string tTitleChooseItemRef {
            get {
                return ResourceManager.GetString("tTitleChooseItemRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose item for Sale.
        /// </summary>
        internal static string tTitleChooseItemRefRtn {
            get {
                return ResourceManager.GetString("tTitleChooseItemRefRtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string tTitleCond {
            get {
                return ResourceManager.GetString("tTitleCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message1.
        /// </summary>
        internal static string tTitleCpnMsg1 {
            get {
                return ResourceManager.GetString("tTitleCpnMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message2.
        /// </summary>
        internal static string tTitleCpnMsg2 {
            get {
                return ResourceManager.GetString("tTitleCpnMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Name.
        /// </summary>
        internal static string tTitleCpnName {
            get {
                return ResourceManager.GetString("tTitleCpnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string tTitleCreditCard {
            get {
                return ResourceManager.GetString("tTitleCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit List.
        /// </summary>
        internal static string tTitleCstBenefit {
            get {
                return ResourceManager.GetString("tTitleCstBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Detail.
        /// </summary>
        internal static string tTitleCstDetail {
            get {
                return ResourceManager.GetString("tTitleCstDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : .
        /// </summary>
        internal static string tTitleCstName {
            get {
                return ResourceManager.GetString("tTitleCstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Available.
        /// </summary>
        internal static string tTitleCstPntAvailable {
            get {
                return ResourceManager.GetString("tTitleCstPntAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point : .
        /// </summary>
        internal static string tTitleCstPoint {
            get {
                return ResourceManager.GetString("tTitleCstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Data for Search.
        /// </summary>
        internal static string tTitleCstSchBtnCstSch {
            get {
                return ResourceManager.GetString("tTitleCstSchBtnCstSch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By RFID.
        /// </summary>
        internal static string tTitleCstSchBtnRFIDSch {
            get {
                return ResourceManager.GetString("tTitleCstSchBtnRFIDSch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Card ID.
        /// </summary>
        internal static string tTitleCstSchByCstCardID {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By CstCode.
        /// </summary>
        internal static string tTitleCstSchByCstCode {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Member Card No..
        /// </summary>
        internal static string tTitleCstSchByCstMemCrdNo {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstMemCrdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        internal static string tTitleCstSchByCstName {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Tax No..
        /// </summary>
        internal static string tTitleCstSchByCstTaxNo {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Phone Number.
        /// </summary>
        internal static string tTitleCstSchByCstTel {
            get {
                return ResourceManager.GetString("tTitleCstSchByCstTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        internal static string tTitleCstSearch {
            get {
                return ResourceManager.GetString("tTitleCstSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        internal static string tTitleDateFrm {
            get {
                return ResourceManager.GetString("tTitleDateFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        internal static string tTitleDateTo {
            get {
                return ResourceManager.GetString("tTitleDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string tTitleNo {
            get {
                return ResourceManager.GetString("tTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string tTitlePdtCode {
            get {
                return ResourceManager.GetString("tTitlePdtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tTitlePdtName {
            get {
                return ResourceManager.GetString("tTitlePdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Other.
        /// </summary>
        internal static string tTitlePdtNameOth {
            get {
                return ResourceManager.GetString("tTitlePdtNameOth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Pos.
        /// </summary>
        internal static string tTitlePosRegister {
            get {
                return ResourceManager.GetString("tTitlePosRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string tTitlePrice {
            get {
                return ResourceManager.GetString("tTitlePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select format to Print.
        /// </summary>
        internal static string tTitlePrnSelect {
            get {
                return ResourceManager.GetString("tTitlePrnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromptPay.
        /// </summary>
        internal static string tTitlePromptPay {
            get {
                return ResourceManager.GetString("tTitlePromptPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Refund Quantity.
        /// </summary>
        internal static string tTitleQty {
            get {
                return ResourceManager.GetString("tTitleQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotas.
        /// </summary>
        internal static string tTitleQuotas {
            get {
                return ResourceManager.GetString("tTitleQuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Available.
        /// </summary>
        internal static string tTitleRedeemAvailable {
            get {
                return ResourceManager.GetString("tTitleRedeemAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Balance.
        /// </summary>
        internal static string tTitleRedeemBalance {
            get {
                return ResourceManager.GetString("tTitleRedeemBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Get Discount.
        /// </summary>
        internal static string tTitleRedeemGetDiscount {
            get {
                return ResourceManager.GetString("tTitleRedeemGetDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Get Product.
        /// </summary>
        internal static string tTitleRedeemGetPdt {
            get {
                return ResourceManager.GetString("tTitleRedeemGetPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Quantity / Bill.
        /// </summary>
        internal static string tTitleRedeemLimitQty {
            get {
                return ResourceManager.GetString("tTitleRedeemLimitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Limit Quantity / Bill.
        /// </summary>
        internal static string tTitleRedeemNotLimitQty {
            get {
                return ResourceManager.GetString("tTitleRedeemNotLimitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balance.
        /// </summary>
        internal static string tTitleRedeemQtyBalance {
            get {
                return ResourceManager.GetString("tTitleRedeemQtyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order.
        /// </summary>
        internal static string tTitleReferSO {
            get {
                return ResourceManager.GetString("tTitleReferSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill remark.
        /// </summary>
        internal static string tTitleRemarkBill {
            get {
                return ResourceManager.GetString("tTitleRemarkBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product remark.
        /// </summary>
        internal static string tTitleRemrkPdt {
            get {
                return ResourceManager.GetString("tTitleRemrkPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter return bill code.
        /// </summary>
        internal static string tTitleReturnBillCode {
            get {
                return ResourceManager.GetString("tTitleReturnBillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return bill code/Tel..
        /// </summary>
        internal static string tTitleReturnBillCodeTel {
            get {
                return ResourceManager.GetString("tTitleReturnBillCodeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search : Product.
        /// </summary>
        internal static string tTitleSearchPdt {
            get {
                return ResourceManager.GetString("tTitleSearchPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        internal static string tTitleSetColorCode {
            get {
                return ResourceManager.GetString("tTitleSetColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Code.
        /// </summary>
        internal static string tTitleTraceCode {
            get {
                return ResourceManager.GetString("tTitleTraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tTitleUnit {
            get {
                return ResourceManager.GetString("tTitleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Number.
        /// </summary>
        internal static string tTitleVehEngine {
            get {
                return ResourceManager.GetString("tTitleVehEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string tTitleVehModel {
            get {
                return ResourceManager.GetString("tTitleVehModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Date.
        /// </summary>
        internal static string tTitleVehSaledate {
            get {
                return ResourceManager.GetString("tTitleVehSaledate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string tTitleVehVIN {
            get {
                return ResourceManager.GetString("tTitleVehVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Car.
        /// </summary>
        internal static string tTitlVehicle {
            get {
                return ResourceManager.GetString("tTitlVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useable Date.
        /// </summary>
        internal static string tUseableDate {
            get {
                return ResourceManager.GetString("tUseableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useable Time.
        /// </summary>
        internal static string tUseableTime {
            get {
                return ResourceManager.GetString("tUseableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string tValue {
            get {
                return ResourceManager.GetString("tValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string tWithdraw {
            get {
                return ResourceManager.GetString("tWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Withdraw !!!.
        /// </summary>
        internal static string tWithdrawHeader {
            get {
                return ResourceManager.GetString("tWithdrawHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Now.
        /// </summary>
        internal static string tWithdrawNow {
            get {
                return ResourceManager.GetString("tWithdrawNow", resourceCulture);
            }
        }
    }
}
