//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSeach_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSeach_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSeach_TH", typeof(resSeach_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกธนาคาร.
        /// </summary>
        internal static string tBank {
            get {
                return ResourceManager.GetString("tBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัส.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกสี.
        /// </summary>
        internal static string tColor {
            get {
                return ResourceManager.GetString("tColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกประเภทคูปอง.
        /// </summary>
        internal static string tCouponType {
            get {
                return ResourceManager.GetString("tCouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกลูกค้า.
        /// </summary>
        internal static string tCst {
            get {
                return ResourceManager.GetString("tCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกสาขา.
        /// </summary>
        internal static string tTitleBch {
            get {
                return ResourceManager.GetString("tTitleBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเครื่องจุดขาย.
        /// </summary>
        internal static string tTitlePos {
            get {
                return ResourceManager.GetString("tTitlePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกหน่วย.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกผู้ใช้.
        /// </summary>
        internal static string tUser {
            get {
                return ResourceManager.GetString("tUser", resourceCulture);
            }
        }
    }
}
