//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resTaxInvoice_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resTaxInvoice_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resTaxInvoice_TH", typeof(resTaxInvoice_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string tAddress {
            get {
                return ResourceManager.GetString("tAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงิน.
        /// </summary>
        internal static string tAmt {
            get {
                return ResourceManager.GetString("tAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้อนุมัติ.
        /// </summary>
        internal static string tApv {
            get {
                return ResourceManager.GetString("tApv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนภาษี.
        /// </summary>
        internal static string tB4Vat {
            get {
                return ResourceManager.GetString("tB4Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสาขา.
        /// </summary>
        internal static string tBchCode {
            get {
                return ResourceManager.GetString("tBchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        internal static string tBranch {
            get {
                return ResourceManager.GetString("tBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทกิจการ.
        /// </summary>
        internal static string tBsnType {
            get {
                return ResourceManager.GetString("tBsnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แคชเชียร์.
        /// </summary>
        internal static string tCasheir {
            get {
                return ResourceManager.GetString("tCasheir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนา.
        /// </summary>
        internal static string tCopy {
            get {
                return ResourceManager.GetString("tCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสลูกค้า.
        /// </summary>
        internal static string tCstCode {
            get {
                return ResourceManager.GetString("tCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า.
        /// </summary>
        internal static string tCstName {
            get {
                return ResourceManager.GetString("tCstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        internal static string tDate {
            get {
                return ResourceManager.GetString("tDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินมัดจำ.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด.
        /// </summary>
        internal static string tDis {
            get {
                return ResourceManager.GetString("tDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่เอกสาร.
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวบรรจง.
        /// </summary>
        internal static string tElaborate {
            get {
                return ResourceManager.GetString("tElaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานประกอบการ.
        /// </summary>
        internal static string tEstab {
            get {
                return ResourceManager.GetString("tEstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แฟกซ์.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำนักงานใหญ่.
        /// </summary>
        internal static string tHQ {
            get {
                return ResourceManager.GetString("tHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บุคคลธรรมดา.
        /// </summary>
        internal static string tIndividual {
            get {
                return ResourceManager.GetString("tIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นิติบุคคล.
        /// </summary>
        internal static string tJuristic {
            get {
                return ResourceManager.GetString("tJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารนี้ผ่านการประมวลผลแล้ว.
        /// </summary>
        internal static string tMsgApproved {
            get {
                return ResourceManager.GetString("tMsgApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกเลขที่เอกสาร.
        /// </summary>
        internal static string tMsgInputDoc {
            get {
                return ResourceManager.GetString("tMsgInputDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อลูกค้า.
        /// </summary>
        internal static string tMsgInputName {
            get {
                return ResourceManager.GetString("tMsgInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกเลขบัตรประจำตัวผู้เสียภาษี.
        /// </summary>
        internal static string tMsgInputTaxNo {
            get {
                return ResourceManager.GetString("tMsgInputTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถพิมพ์ได้ เนื่องจากเอกสารยังไม่ได้ถูกสร้าง.
        /// </summary>
        internal static string tMsgNotPrint {
            get {
                return ResourceManager.GetString("tMsgNotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การประมวลผลเสร็จสมบูรณ์.
        /// </summary>
        internal static string tMsgPrcComplete {
            get {
                return ResourceManager.GetString("tMsgPrcComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกแก้ไขข้อมูลเรียบร้อยแล้ว.
        /// </summary>
        internal static string tMsgSave {
            get {
                return ResourceManager.GetString("tMsgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่.
        /// </summary>
        internal static string tNo {
            get {
                return ResourceManager.GetString("tNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเว้นภาษี.
        /// </summary>
        internal static string tNonVat {
            get {
                return ResourceManager.GetString("tNonVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสินค้า.
        /// </summary>
        internal static string tPdtDetail {
            get {
                return ResourceManager.GetString("tPdtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        internal static string tPdtID {
            get {
                return ResourceManager.GetString("tPdtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องจุดขาย.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับโดย.
        /// </summary>
        internal static string tReceive {
            get {
                return ResourceManager.GetString("tReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างอิงถึงเอกสาร.
        /// </summary>
        internal static string tRefDoc {
            get {
                return ResourceManager.GetString("tRefDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงานขาย.
        /// </summary>
        internal static string tSaleman {
            get {
                return ResourceManager.GetString("tSaleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งโดย.
        /// </summary>
        internal static string tSend {
            get {
                return ResourceManager.GetString("tSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string tSeq {
            get {
                return ResourceManager.GetString("tSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        internal static string tSum {
            get {
                return ResourceManager.GetString("tSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมจำนวนเงินทั้งสิ้น.
        /// </summary>
        internal static string tSumAmt {
            get {
                return ResourceManager.GetString("tSumAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนรวม.
        /// </summary>
        internal static string tSumQty {
            get {
                return ResourceManager.GetString("tSumQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบกำกับภาษี.
        /// </summary>
        internal static string tTax {
            get {
                return ResourceManager.GetString("tTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำตัวผู้เสียภาษี.
        /// </summary>
        internal static string tTaxID {
            get {
                return ResourceManager.GetString("tTaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string tTitleAddr1 {
            get {
                return ResourceManager.GetString("tTitleAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string tTitleAddr2 {
            get {
                return ResourceManager.GetString("tTitleAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวมหลัง ลด/ชาร์จ.
        /// </summary>
        internal static string tTitleAftDisChg {
            get {
                return ResourceManager.GetString("tTitleAftDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลูกค้า.
        /// </summary>
        internal static string tTitleCst {
            get {
                return ResourceManager.GetString("tTitleCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า/ชื่อออกใบกำกับภาษี.
        /// </summary>
        internal static string tTitleCstNameTax {
            get {
                return ResourceManager.GetString("tTitleCstNameTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลด/ชาร์จ.
        /// </summary>
        internal static string tTitleDisChg {
            get {
                return ResourceManager.GetString("tTitleDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวมสุทธิ.
        /// </summary>
        internal static string tTitleNet {
            get {
                return ResourceManager.GetString("tTitleNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบกำกับภาษีอย่างย่อ.
        /// </summary>
        internal static string tTitleSlipNo {
            get {
                return ResourceManager.GetString("tTitleSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบกำกับภาษีเต็มรูป.
        /// </summary>
        internal static string tTitleTaxNo {
            get {
                return ResourceManager.GetString("tTitleTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        internal static string tTitleTotal {
            get {
                return ResourceManager.GetString("tTitleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวมภาษีมูลค่าเพิ่ม.
        /// </summary>
        internal static string tTitleTotalVat {
            get {
                return ResourceManager.GetString("tTitleTotalVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        internal static string tTitleUnit {
            get {
                return ResourceManager.GetString("tTitleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมจำนวนเงิน.
        /// </summary>
        internal static string tTotalAmt {
            get {
                return ResourceManager.GetString("tTotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษีมูลค่าเพิ่ม.
        /// </summary>
        internal static string tVat {
            get {
                return ResourceManager.GetString("tVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขริสแบนด์ / บัตร.
        /// </summary>
        internal static string tWBNo {
            get {
                return ResourceManager.GetString("tWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีภาษี.
        /// </summary>
        internal static string tWithTax {
            get {
                return ResourceManager.GetString("tWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ริสแบนด์ / บัตร.
        /// </summary>
        internal static string tWristband {
            get {
                return ResourceManager.GetString("tWristband", resourceCulture);
            }
        }
    }
}
