//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSync_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSync_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSync_EN", typeof(resSync_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date compare.
        /// </summary>
        internal static string tDateCompare {
            get {
                return ResourceManager.GetString("tDateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string tDownload {
            get {
                return ResourceManager.GetString("tDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date.
        /// </summary>
        internal static string tLastDate {
            get {
                return ResourceManager.GetString("tLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check from last sync.
        /// </summary>
        internal static string tRecentUpdate {
            get {
                return ResourceManager.GetString("tRecentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string tSelectAll {
            get {
                return ResourceManager.GetString("tSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string tSuccess {
            get {
                return ResourceManager.GetString("tSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Download Error.
        /// </summary>
        internal static string tSycDwnError {
            get {
                return ResourceManager.GetString("tSycDwnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Download Success.
        /// </summary>
        internal static string tSycDwnSuccess {
            get {
                return ResourceManager.GetString("tSycDwnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last date.
        /// </summary>
        internal static string tTitleLastDateDwn {
            get {
                return ResourceManager.GetString("tTitleLastDateDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last date.
        /// </summary>
        internal static string tTitleLastDateUpl {
            get {
                return ResourceManager.GetString("tTitleLastDateUpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        internal static string tTitleNameDwn {
            get {
                return ResourceManager.GetString("tTitleNameDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tTitleNameUpl {
            get {
                return ResourceManager.GetString("tTitleNameUpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccess.
        /// </summary>
        internal static string tUnSuccess {
            get {
                return ResourceManager.GetString("tUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string tUpload {
            get {
                return ResourceManager.GetString("tUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Success.
        /// </summary>
        internal static string tUploadSuccess {
            get {
                return ResourceManager.GetString("tUploadSuccess", resourceCulture);
            }
        }
    }
}
