//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSale_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSale_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSale_EN", typeof(resSale_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Quantity.
        /// </summary>
        internal static string tChgQty {
            get {
                return ResourceManager.GetString("tChgQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string tFavor {
            get {
                return ResourceManager.GetString("tFavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product group.
        /// </summary>
        internal static string tGroupPdt {
            get {
                return ResourceManager.GetString("tGroupPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Cst.
        /// </summary>
        internal static string tGrpCst {
            get {
                return ResourceManager.GetString("tGrpCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Scan.
        /// </summary>
        internal static string tModeScan {
            get {
                return ResourceManager.GetString("tModeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Touchscreen.
        /// </summary>
        internal static string tModeTouch {
            get {
                return ResourceManager.GetString("tModeTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not back if there are some items in bill.
        /// </summary>
        internal static string tMsgCantBack {
            get {
                return ResourceManager.GetString("tMsgCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not select new customers if there are some items on the bil.
        /// </summary>
        internal static string tMsgCantSelectCst {
            get {
                return ResourceManager.GetString("tMsgCantSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not select sale order if there are some items on the bil.
        /// </summary>
        internal static string tMsgCantSO {
            get {
                return ResourceManager.GetString("tMsgCantSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill is not in return conditions !!!.
        /// </summary>
        internal static string tMsgErrRetrunBill {
            get {
                return ResourceManager.GetString("tMsgErrRetrunBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found data or not defenined yet..
        /// </summary>
        internal static string tMsgNotFoundPdt {
            get {
                return ResourceManager.GetString("tMsgNotFoundPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Quantity.
        /// </summary>
        internal static string tNewQty {
            get {
                return ResourceManager.GetString("tNewQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Quantity.
        /// </summary>
        internal static string tOldQty {
            get {
                return ResourceManager.GetString("tOldQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Group.
        /// </summary>
        internal static string tPriGrp {
            get {
                return ResourceManager.GetString("tPriGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer to bill.
        /// </summary>
        internal static string tRefer {
            get {
                return ResourceManager.GetString("tRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        internal static string tRental {
            get {
                return ResourceManager.GetString("tRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string tScan {
            get {
                return ResourceManager.GetString("tScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Customer.
        /// </summary>
        internal static string tSelectCst {
            get {
                return ResourceManager.GetString("tSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort A-Z.
        /// </summary>
        internal static string tSortAZ {
            get {
                return ResourceManager.GetString("tSortAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Z-A.
        /// </summary>
        internal static string tSortZA {
            get {
                return ResourceManager.GetString("tSortZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string tTelephone {
            get {
                return ResourceManager.GetString("tTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date :.
        /// </summary>
        internal static string tTitleExpd {
            get {
                return ResourceManager.GetString("tTitleExpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point :.
        /// </summary>
        internal static string tTitlePoint {
            get {
                return ResourceManager.GetString("tTitlePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Level :.
        /// </summary>
        internal static string tTitlePriLev {
            get {
                return ResourceManager.GetString("tTitlePriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Sale.
        /// </summary>
        internal static string tTitleReferBill {
            get {
                return ResourceManager.GetString("tTitleReferBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer Bliil Return.
        /// </summary>
        internal static string tTitleReferBillRtn {
            get {
                return ResourceManager.GetString("tTitleReferBillRtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order :.
        /// </summary>
        internal static string tTitleSO {
            get {
                return ResourceManager.GetString("tTitleSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image product.
        /// </summary>
        internal static string tViewPdtImg {
            get {
                return ResourceManager.GetString("tViewPdtImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List product.
        /// </summary>
        internal static string tViewPdtList {
            get {
                return ResourceManager.GetString("tViewPdtList", resourceCulture);
            }
        }
    }
}
