//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQReceivePrc.Resources_String {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resGlobal_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resGlobal_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MQReceivePrc.Resources_String.resGlobal_TH", typeof(resGlobal_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่า.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกบิล.
        /// </summary>
        internal static string tCancelBill {
            get {
                return ResourceManager.GetString("tCancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สกุลเงิน.
        /// </summary>
        internal static string tCurrency {
            get {
                return ResourceManager.GetString("tCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความถี่.
        /// </summary>
        internal static string tFreq {
            get {
                return ResourceManager.GetString("tFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พักบิล.
        /// </summary>
        internal static string tHoldBill {
            get {
                return ResourceManager.GetString("tHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเงินเข้า.
        /// </summary>
        internal static string tMnyIn {
            get {
                return ResourceManager.GetString("tMnyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเงินออก.
        /// </summary>
        internal static string tMnyOut {
            get {
                return ResourceManager.GetString("tMnyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดลิ้นชักไม่ขาย.
        /// </summary>
        internal static string tOpDrwNoS {
            get {
                return ResourceManager.GetString("tOpDrwNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปยอดขายสินค้าควบคุมพิเศษ.
        /// </summary>
        internal static string tPdtSpcSum {
            get {
                return ResourceManager.GetString("tPdtSpcSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขเครื่อง.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์วันที่.
        /// </summary>
        internal static string tPrintDate {
            get {
                return ResourceManager.GetString("tPrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคืน.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคืนสินค้า.
        /// </summary>
        internal static string tRefundAmt {
            get {
                return ResourceManager.GetString("tRefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลคืน จาก.
        /// </summary>
        internal static string tRefundFrm {
            get {
                return ResourceManager.GetString("tRefundFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลคืน ถึง.
        /// </summary>
        internal static string tRefundTo {
            get {
                return ResourceManager.GetString("tRefundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขาย.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขาย.
        /// </summary>
        internal static string tSaleAmt {
            get {
                return ResourceManager.GetString("tSaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขาย.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลขาย จาก.
        /// </summary>
        internal static string tSaleFrm {
            get {
                return ResourceManager.GetString("tSaleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลขาย ถึง.
        /// </summary>
        internal static string tSaleTo {
            get {
                return ResourceManager.GetString("tSaleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! ปิดการขาย !!!.
        /// </summary>
        internal static string tShiftSUM {
            get {
                return ResourceManager.GetString("tShiftSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปการรับชำระเงิน(สกุลเงิน).
        /// </summary>
        internal static string tSumCurrency {
            get {
                return ResourceManager.GetString("tSumCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมเงิน.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ใช้.
        /// </summary>
        internal static string tUsr {
            get {
                return ResourceManager.GetString("tUsr", resourceCulture);
            }
        }
    }
}
