//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQReceivePrc.Resources_String {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resGlobal_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resGlobal_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MQReceivePrc.Resources_String.resGlobal_EN", typeof(resGlobal_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Bill.
        /// </summary>
        internal static string tCancelBill {
            get {
                return ResourceManager.GetString("tCancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string tCurrency {
            get {
                return ResourceManager.GetString("tCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string tFreq {
            get {
                return ResourceManager.GetString("tFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Bill.
        /// </summary>
        internal static string tHoldBill {
            get {
                return ResourceManager.GetString("tHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money In.
        /// </summary>
        internal static string tMnyIn {
            get {
                return ResourceManager.GetString("tMnyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Out.
        /// </summary>
        internal static string tMnyOut {
            get {
                return ResourceManager.GetString("tMnyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpDrw.(No S).
        /// </summary>
        internal static string tOpDrwNoS {
            get {
                return ResourceManager.GetString("tOpDrwNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Product Amount.
        /// </summary>
        internal static string tPdtSpcSum {
            get {
                return ResourceManager.GetString("tPdtSpcSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print-Date.
        /// </summary>
        internal static string tPrintDate {
            get {
                return ResourceManager.GetString("tPrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Amt.
        /// </summary>
        internal static string tRefundAmt {
            get {
                return ResourceManager.GetString("tRefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return From.
        /// </summary>
        internal static string tRefundFrm {
            get {
                return ResourceManager.GetString("tRefundFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To.
        /// </summary>
        internal static string tRefundTo {
            get {
                return ResourceManager.GetString("tRefundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amt.
        /// </summary>
        internal static string tSaleAmt {
            get {
                return ResourceManager.GetString("tSaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sale.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale From.
        /// </summary>
        internal static string tSaleFrm {
            get {
                return ResourceManager.GetString("tSaleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale To.
        /// </summary>
        internal static string tSaleTo {
            get {
                return ResourceManager.GetString("tSaleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Sign Out !!!.
        /// </summary>
        internal static string tShiftSUM {
            get {
                return ResourceManager.GetString("tShiftSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment summary(Currency).
        /// </summary>
        internal static string tSumCurrency {
            get {
                return ResourceManager.GetString("tSumCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string tUsr {
            get {
                return ResourceManager.GetString("tUsr", resourceCulture);
            }
        }
    }
}
