//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resGlobal_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resGlobal_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Global.resGlobal_EN", typeof(resGlobal_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tAbout {
            get {
                return ResourceManager.GetString("tAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string tAdd {
            get {
                return ResourceManager.GetString("tAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string tAddr1 {
            get {
                return ResourceManager.GetString("tAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string tAddr2 {
            get {
                return ResourceManager.GetString("tAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc./Product.
        /// </summary>
        internal static string tAmtDis {
            get {
                return ResourceManager.GetString("tAmtDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string tBack {
            get {
                return ResourceManager.GetString("tBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Bank note.
        /// </summary>
        internal static string tBanknote {
            get {
                return ResourceManager.GetString("tBanknote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string tBarcode {
            get {
                return ResourceManager.GetString("tBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill List.
        /// </summary>
        internal static string tBillList {
            get {
                return ResourceManager.GetString("tBillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string tCalculate {
            get {
                return ResourceManager.GetString("tCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Bill.
        /// </summary>
        internal static string tCancelBill {
            get {
                return ResourceManager.GetString("tCancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original price.
        /// </summary>
        internal static string tCancelNewPri {
            get {
                return ResourceManager.GetString("tCancelNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Top-up.
        /// </summary>
        internal static string tCancelTopup {
            get {
                return ResourceManager.GetString("tCancelTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Card.
        /// </summary>
        internal static string tCardNo {
            get {
                return ResourceManager.GetString("tCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        internal static string tCardType {
            get {
                return ResourceManager.GetString("tCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        internal static string tCashier {
            get {
                return ResourceManager.GetString("tCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string tChange {
            get {
                return ResourceManager.GetString("tChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chg..
        /// </summary>
        internal static string tChg {
            get {
                return ResourceManager.GetString("tChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Promotion.
        /// </summary>
        internal static string tChkPmt {
            get {
                return ResourceManager.GetString("tChkPmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new price.
        /// </summary>
        internal static string tConfirmNewPri {
            get {
                return ResourceManager.GetString("tConfirmNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string tCopy {
            get {
                return ResourceManager.GetString("tCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        internal static string tCoupon {
            get {
                return ResourceManager.GetString("tCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Coupon.
        /// </summary>
        internal static string tCpnDis {
            get {
                return ResourceManager.GetString("tCpnDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Redeem.
        /// </summary>
        internal static string tCpnRd {
            get {
                return ResourceManager.GetString("tCpnRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt..
        /// </summary>
        internal static string tCS_Amt {
            get {
                return ResourceManager.GetString("tCS_Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Hold Bill !!!.
        /// </summary>
        internal static string tCS_HoldBill {
            get {
                return ResourceManager.GetString("tCS_HoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tCS_RcvType {
            get {
                return ResourceManager.GetString("tCS_RcvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string tCS_Receiver {
            get {
                return ResourceManager.GetString("tCS_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string tCS_Sender {
            get {
                return ResourceManager.GetString("tCS_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq..
        /// </summary>
        internal static string tCS_Seq {
            get {
                return ResourceManager.GetString("tCS_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Bank note.
        /// </summary>
        internal static string tCS_ShiftBNK {
            get {
                return ResourceManager.GetString("tCS_ShiftBNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receving Summary.
        /// </summary>
        internal static string tCS_ShiftRcv {
            get {
                return ResourceManager.GetString("tCS_ShiftRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Sign Out !!!.
        /// </summary>
        internal static string tCS_ShiftSUM {
            get {
                return ResourceManager.GetString("tCS_ShiftSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string tCS_TotalAmt {
            get {
                return ResourceManager.GetString("tCS_TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Cancel Bill !!!.
        /// </summary>
        internal static string tCS_VoidBill {
            get {
                return ResourceManager.GetString("tCS_VoidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code..
        /// </summary>
        internal static string tCstCode {
            get {
                return ResourceManager.GetString("tCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string tCstCredit {
            get {
                return ResourceManager.GetString("tCstCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string tCurrency {
            get {
                return ResourceManager.GetString("tCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string tDatetime {
            get {
                return ResourceManager.GetString("tDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string tDel {
            get {
                return ResourceManager.GetString("tDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string tDetail {
            get {
                return ResourceManager.GetString("tDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dis..
        /// </summary>
        internal static string tDis {
            get {
                return ResourceManager.GetString("tDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string tDoc {
            get {
                return ResourceManager.GetString("tDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string tDownload {
            get {
                return ResourceManager.GetString("tDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tExit {
            get {
                return ResourceManager.GetString("tExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expired.
        /// </summary>
        internal static string tExpire {
            get {
                return ResourceManager.GetString("tExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string tFactor {
            get {
                return ResourceManager.GetString("tFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string tFavorite {
            get {
                return ResourceManager.GetString("tFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Data.
        /// </summary>
        internal static string tFilter {
            get {
                return ResourceManager.GetString("tFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string tFreq {
            get {
                return ResourceManager.GetString("tFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing function..
        /// </summary>
        internal static string tFuncError {
            get {
                return ResourceManager.GetString("tFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Promotion.
        /// </summary>
        internal static string tGetPromotion {
            get {
                return ResourceManager.GetString("tGetPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Cst.
        /// </summary>
        internal static string tGrpCst {
            get {
                return ResourceManager.GetString("tGrpCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tHelp {
            get {
                return ResourceManager.GetString("tHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Bill.
        /// </summary>
        internal static string tHoldBill {
            get {
                return ResourceManager.GetString("tHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string tInformation {
            get {
                return ResourceManager.GetString("tInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string tKeyboard {
            get {
                return ResourceManager.GetString("tKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen .
        /// </summary>
        internal static string tLockKb {
            get {
                return ResourceManager.GetString("tLockKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money In.
        /// </summary>
        internal static string tMnyIn {
            get {
                return ResourceManager.GetString("tMnyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Out.
        /// </summary>
        internal static string tMnyOut {
            get {
                return ResourceManager.GetString("tMnyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string tMsg_Col {
            get {
                return ResourceManager.GetString("tMsg_Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string tMsg_Pdt {
            get {
                return ResourceManager.GetString("tMsg_Pdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string tMsg_Pos {
            get {
                return ResourceManager.GetString("tMsg_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string tMsg_Qty {
            get {
                return ResourceManager.GetString("tMsg_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string tMsg_Row {
            get {
                return ResourceManager.GetString("tMsg_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input amount more than 0.
        /// </summary>
        internal static string tMsgAmountZero {
            get {
                return ResourceManager.GetString("tMsgAmountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount value more than the amount allowed to be reduced !!!.
        /// </summary>
        internal static string tMsgAmtDisAlw {
            get {
                return ResourceManager.GetString("tMsgAmtDisAlw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization is not define.
        /// </summary>
        internal static string tMsgAuthNotDefine {
            get {
                return ResourceManager.GetString("tMsgAuthNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Branch ID not define.
        /// </summary>
        internal static string tMsgBchRefIDNotDefine {
            get {
                return ResourceManager.GetString("tMsgBchRefIDNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales error occurred. Please cancel bill and try again to sale.
        /// </summary>
        internal static string tMsgBillNotComplete {
            get {
                return ResourceManager.GetString("tMsgBillNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create document.
        /// </summary>
        internal static string tMsgCannotCreateDoc {
            get {
                return ResourceManager.GetString("tMsgCannotCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not permission.
        /// </summary>
        internal static string tMsgCannotOpen {
            get {
                return ResourceManager.GetString("tMsgCannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not back if there are some items in bill.
        /// </summary>
        internal static string tMsgCantBack {
            get {
                return ResourceManager.GetString("tMsgCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please search by phone number or another ID card number..
        /// </summary>
        internal static string tMsgCantCreateCst {
            get {
                return ResourceManager.GetString("tMsgCantCreateCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service not response..
        /// </summary>
        internal static string tMsgCantService {
            get {
                return ResourceManager.GetString("tMsgCantService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service not response, Please contact the administrator..
        /// </summary>
        internal static string tMsgCantServiceKADS {
            get {
                return ResourceManager.GetString("tMsgCantServiceKADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Change is over than {0} unit. Please input again.
        /// </summary>
        internal static string tMsgChgOver {
            get {
                return ResourceManager.GetString("tMsgChgOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close the shift, because there is bill hold item !!!  Want to clear Items bill Hold ?.
        /// </summary>
        internal static string tMsgChkHoldBill {
            get {
                return ResourceManager.GetString("tMsgChkHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has a discount. If you want to change the quantity of this product The discount will be removed. Do you want to continue ?.
        /// </summary>
        internal static string tMsgClearDisc {
            get {
                return ResourceManager.GetString("tMsgClearDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click button accept for check wristband / card no..
        /// </summary>
        internal static string tMsgClickAccept {
            get {
                return ResourceManager.GetString("tMsgClickAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connent URL Success.
        /// </summary>
        internal static string tMsgConnUrlSuccess {
            get {
                return ResourceManager.GetString("tMsgConnUrlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found !!!.
        /// </summary>
        internal static string tMsgDataNotFound {
            get {
                return ResourceManager.GetString("tMsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This discount is not allowed use. According to the Set discount policy..
        /// </summary>
        internal static string tMsgDiscPolicyNotAlw {
            get {
                return ResourceManager.GetString("tMsgDiscPolicyNotAlw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount amount is more than Amount. can discount.
        /// </summary>
        internal static string tMsgDisOver {
            get {
                return ResourceManager.GetString("tMsgDisOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Connect to Internet Connection , Please Check Your Connection..
        /// </summary>
        internal static string tMsgErrCon {
            get {
                return ResourceManager.GetString("tMsgErrCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, unable to proceed sale. Please contact administrator..
        /// </summary>
        internal static string tMsgErrNotSale {
            get {
                return ResourceManager.GetString("tMsgErrNotSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to exit?.
        /// </summary>
        internal static string tMsgExit {
            get {
                return ResourceManager.GetString("tMsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not charge or discount when payment was received.
        /// </summary>
        internal static string tMsgFirstPay {
            get {
                return ResourceManager.GetString("tMsgFirstPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function unavailable if there are some items in selling grid..
        /// </summary>
        internal static string tMsgHaveItem {
            get {
                return ResourceManager.GetString("tMsgHaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to hold bill?.
        /// </summary>
        internal static string tMsgHoldBill {
            get {
                return ResourceManager.GetString("tMsgHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input amount.
        /// </summary>
        internal static string tMsgInputAmount {
            get {
                return ResourceManager.GetString("tMsgInputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Username and Password.
        /// </summary>
        internal static string tMsgInputUsrPwd {
            get {
                return ResourceManager.GetString("tMsgInputUsrPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Wristband no. / Card No..
        /// </summary>
        internal static string tMsgInputWristband {
            get {
                return ResourceManager.GetString("tMsgInputWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect DateTime format.
        /// </summary>
        internal static string tMsgInvalidDate {
            get {
                return ResourceManager.GetString("tMsgInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password is wrong.
        /// </summary>
        internal static string tMsgInvalidUsr {
            get {
                return ResourceManager.GetString("tMsgInvalidUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is wrong.
        /// </summary>
        internal static string tMsgInvalidUsrname {
            get {
                return ResourceManager.GetString("tMsgInvalidUsrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KubotaID Not Found !!!.
        /// </summary>
        internal static string tMsgKubotaIDNotFound {
            get {
                return ResourceManager.GetString("tMsgKubotaIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of open shift. Must be within the current 1 year..
        /// </summary>
        internal static string tMsgLongTime {
            get {
                return ResourceManager.GetString("tMsgLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any data to do the function..
        /// </summary>
        internal static string tMsgNoData {
            get {
                return ResourceManager.GetString("tMsgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any items in grid to do the function..
        /// </summary>
        internal static string tMsgNoItem {
            get {
                return ResourceManager.GetString("tMsgNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have url web service, Please contact the administrator..
        /// </summary>
        internal static string tMsgNoService {
            get {
                return ResourceManager.GetString("tMsgNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot discount this invoice after charge.
        /// </summary>
        internal static string tMsgNotAlwDisAftChg {
            get {
                return ResourceManager.GetString("tMsgNotAlwDisAftChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer is not allowed to use points !!!.
        /// </summary>
        internal static string tMsgNotAlwRedeem {
            get {
                return ResourceManager.GetString("tMsgNotAlwRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go to back the sales page. Because the new price has been confirmed.
        /// </summary>
        internal static string tMsgNotBackSale {
            get {
                return ResourceManager.GetString("tMsgNotBackSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Choose Customer..
        /// </summary>
        internal static string tMsgNotChooseCst {
            get {
                return ResourceManager.GetString("tMsgNotChooseCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect URL.
        /// </summary>
        internal static string tMsgNotConnUrl {
            get {
                return ResourceManager.GetString("tMsgNotConnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Wristband No. / Card No. : {0}.
        /// </summary>
        internal static string tMsgNotfoundCard {
            get {
                return ResourceManager.GetString("tMsgNotfoundCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not login because other user has not closed shift yet
        ///Please press Yes to close the previous sales shift. And open a new sales shift.
        ///Please press No to allow the user to open the shift and close the previous shift..
        /// </summary>
        internal static string tMsgOpenShift {
            get {
                return ResourceManager.GetString("tMsgOpenShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, do you want to accept all balance?.
        /// </summary>
        internal static string tMsgPayConfirm {
            get {
                return ResourceManager.GetString("tMsgPayConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying by Coupon and Cheque and RedeemPoint, receiving money must less than or equal total amount..
        /// </summary>
        internal static string tMsgPayMost {
            get {
                return ResourceManager.GetString("tMsgPayMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos is not define..
        /// </summary>
        internal static string tMsgPosNotDefine {
            get {
                return ResourceManager.GetString("tMsgPosNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration expires Please contact the system administrator..
        /// </summary>
        internal static string tMsgPosRegExprie {
            get {
                return ResourceManager.GetString("tMsgPosRegExprie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This POS has already been registered with another Mac Address..
        /// </summary>
        internal static string tMsgPosRegistered {
            get {
                return ResourceManager.GetString("tMsgPosRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration number is invalid. Please notify the system administrator..
        /// </summary>
        internal static string tMsgPosRegNotMatch {
            get {
                return ResourceManager.GetString("tMsgPosRegNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This POS is not registered. Please register.
        /// </summary>
        internal static string tMsgPosRegNotRegistered {
            get {
                return ResourceManager.GetString("tMsgPosRegNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration format.
        /// </summary>
        internal static string tMsgPosRegTokenFmtInvalid {
            get {
                return ResourceManager.GetString("tMsgPosRegTokenFmtInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered wait for approval..
        /// </summary>
        internal static string tMsgPosRegWaitApv {
            get {
                return ResourceManager.GetString("tMsgPosRegWaitApv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Return bill code/Tel..
        /// </summary>
        internal static string tMsgReqReturnBillCode {
            get {
                return ResourceManager.GetString("tMsgReqReturnBillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Sale Amount.
        /// </summary>
        internal static string tMsgShiftCheck {
            get {
                return ResourceManager.GetString("tMsgShiftCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Shift is not the current day. Please close  Shift !!!.
        /// </summary>
        internal static string tMsgShiftDateInvalid {
            get {
                return ResourceManager.GetString("tMsgShiftDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This POS is not registered or the registration of this POS has expired !!!.
        /// </summary>
        internal static string tMsgStaPosRegFalse {
            get {
                return ResourceManager.GetString("tMsgStaPosRegFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to use {0}Branch Code : {1}Pos Code : {2}Mac Address No. : {3}Expired Date : {4}.
        /// </summary>
        internal static string tMsgStaPosRegistered {
            get {
                return ResourceManager.GetString("tMsgStaPosRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL API2ARDoc is not define.
        /// </summary>
        internal static string tMsgUrlARDocNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlARDocNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL APIKADS Check Stock Online is not define.
        /// </summary>
        internal static string tMsgUrlChkStkNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlChkStkNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL API for search customer is not define.
        /// </summary>
        internal static string tMsgUrlCstSchNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlCstSchNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL API for get token is not define.
        /// </summary>
        internal static string tMsgUrlGetTokenNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlGetTokenNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL API2PSMaster is not define.
        /// </summary>
        internal static string tMsgUrlMasterNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlMasterNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input url web service store.
        /// </summary>
        internal static string tMsgURLStore {
            get {
                return ResourceManager.GetString("tMsgURLStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL APIKADS Vehicle is not define.
        /// </summary>
        internal static string tMsgUrlVehicleNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlVehicleNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL API2FNWallet is not define.
        /// </summary>
        internal static string tMsgUrlWalletNotDefine {
            get {
                return ResourceManager.GetString("tMsgUrlWalletNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to void bill?.
        /// </summary>
        internal static string tMsgVoidBill {
            get {
                return ResourceManager.GetString("tMsgVoidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Wahouse Code not define.
        /// </summary>
        internal static string tMsgWahRefCodeNotDefine {
            get {
                return ResourceManager.GetString("tMsgWahRefCodeNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * When confirming the new price The system will clear all discounts / charges..
        /// </summary>
        internal static string tMsgWarnigClear {
            get {
                return ResourceManager.GetString("tMsgWarnigClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to work..
        /// </summary>
        internal static string tMsgWelcome {
            get {
                return ResourceManager.GetString("tMsgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price.
        /// </summary>
        internal static string tNewPrice {
            get {
                return ResourceManager.GetString("tNewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no amout that can be discount / charged..
        /// </summary>
        internal static string tNoAmtDisChg {
            get {
                return ResourceManager.GetString("tNoAmtDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpDrw.(No S).
        /// </summary>
        internal static string tOpDrwNoS {
            get {
                return ResourceManager.GetString("tOpDrwNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ori. Price.
        /// </summary>
        internal static string tOriPrice {
            get {
                return ResourceManager.GetString("tOriPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override on screen .
        /// </summary>
        internal static string tOverride {
            get {
                return ResourceManager.GetString("tOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} data. Page {1} / {2}.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {1} / {2}.
        /// </summary>
        internal static string tPagePay {
            get {
                return ResourceManager.GetString("tPagePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Part of Field.
        /// </summary>
        internal static string tPartField {
            get {
                return ResourceManager.GetString("tPartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string tPassword {
            get {
                return ResourceManager.GetString("tPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string tPay {
            get {
                return ResourceManager.GetString("tPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string tPdtCode {
            get {
                return ResourceManager.GetString("tPdtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want this product to be free item?.
        /// </summary>
        internal static string tPdtFree {
            get {
                return ResourceManager.GetString("tPdtFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        internal static string tPdtList {
            get {
                return ResourceManager.GetString("tPdtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Product Amount.
        /// </summary>
        internal static string tPdtSpcSum {
            get {
                return ResourceManager.GetString("tPdtSpcSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking List.
        /// </summary>
        internal static string tPickinglist {
            get {
                return ResourceManager.GetString("tPickinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string tPreview {
            get {
                return ResourceManager.GetString("tPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string tPrint {
            get {
                return ResourceManager.GetString("tPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print-Date.
        /// </summary>
        internal static string tPrintDate {
            get {
                return ResourceManager.GetString("tPrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        internal static string tPrivilege {
            get {
                return ResourceManager.GetString("tPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string tPromotion {
            get {
                return ResourceManager.GetString("tPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Amount.
        /// </summary>
        internal static string tQuickAmt {
            get {
                return ResourceManager.GetString("tQuickAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Get Discount.
        /// </summary>
        internal static string tRdDis {
            get {
                return ResourceManager.GetString("tRdDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Get Product.
        /// </summary>
        internal static string tRdPdt {
            get {
                return ResourceManager.GetString("tRdPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string tReason {
            get {
                return ResourceManager.GetString("tReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string tReceive {
            get {
                return ResourceManager.GetString("tReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string tReceiver {
            get {
                return ResourceManager.GetString("tReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomed Promotion.
        /// </summary>
        internal static string tRecomed {
            get {
                return ResourceManager.GetString("tRecomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. No.
        /// </summary>
        internal static string tRefer {
            get {
                return ResourceManager.GetString("tRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Amt.
        /// </summary>
        internal static string tRefundAmt {
            get {
                return ResourceManager.GetString("tRefundAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return From.
        /// </summary>
        internal static string tRefundFrm {
            get {
                return ResourceManager.GetString("tRefundFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Refund !.
        /// </summary>
        internal static string tRefundPdt {
            get {
                return ResourceManager.GetString("tRefundPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To.
        /// </summary>
        internal static string tRefundTo {
            get {
                return ResourceManager.GetString("tRefundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return bill code.
        /// </summary>
        internal static string tReturnBillCode {
            get {
                return ResourceManager.GetString("tReturnBillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Rcv.
        /// </summary>
        internal static string tRoundRcv {
            get {
                return ResourceManager.GetString("tRoundRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amt.
        /// </summary>
        internal static string tSaleAmt {
            get {
                return ResourceManager.GetString("tSaleAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sale.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale From.
        /// </summary>
        internal static string tSaleFrm {
            get {
                return ResourceManager.GetString("tSaleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saling Summary Report.
        /// </summary>
        internal static string tSaleSumRpt {
            get {
                return ResourceManager.GetString("tSaleSumRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale To.
        /// </summary>
        internal static string tSaleTo {
            get {
                return ResourceManager.GetString("tSaleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        internal static string tSchBy {
            get {
                return ResourceManager.GetString("tSchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Document.
        /// </summary>
        internal static string tSchDoc {
            get {
                return ResourceManager.GetString("tSchDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string tSender {
            get {
                return ResourceManager.GetString("tSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string tSeq {
            get {
                return ResourceManager.GetString("tSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string tSet {
            get {
                return ResourceManager.GetString("tSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Code.
        /// </summary>
        internal static string tShiftCode {
            get {
                return ResourceManager.GetString("tShiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function keyboard.
        /// </summary>
        internal static string tShowKb {
            get {
                return ResourceManager.GetString("tShowKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string tSlpChange {
            get {
                return ResourceManager.GetString("tSlpChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        internal static string tSlpMemCard {
            get {
                return ResourceManager.GetString("tSlpMemCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem ID.
        /// </summary>
        internal static string tSlpMemCode {
            get {
                return ResourceManager.GetString("tSlpMemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exprire.
        /// </summary>
        internal static string tSlpMemExpire {
            get {
                return ResourceManager.GetString("tSlpMemExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Pt..
        /// </summary>
        internal static string tSlpMemLastPt {
            get {
                return ResourceManager.GetString("tSlpMemLastPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pmt pt..
        /// </summary>
        internal static string tSlpMemPmtPt {
            get {
                return ResourceManager.GetString("tSlpMemPmtPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg Pt..
        /// </summary>
        internal static string tSlpMemRegPt {
            get {
                return ResourceManager.GetString("tSlpMemRegPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Point.
        /// </summary>
        internal static string tSlpMemTotalPt {
            get {
                return ResourceManager.GetString("tSlpMemTotalPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Rcv.
        /// </summary>
        internal static string tSlpRound {
            get {
                return ResourceManager.GetString("tSlpRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string tSlpSubTotal {
            get {
                return ResourceManager.GetString("tSlpSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string tSlpTotal {
            get {
                return ResourceManager.GetString("tSlpTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string tSlpUsrName {
            get {
                return ResourceManager.GetString("tSlpUsrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string tSlpVat {
            get {
                return ResourceManager.GetString("tSlpVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatable.
        /// </summary>
        internal static string tSlpVatable {
            get {
                return ResourceManager.GetString("tSlpVatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Included.
        /// </summary>
        internal static string tSlpVatIncluded {
            get {
                return ResourceManager.GetString("tSlpVatIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse does not check stock online..
        /// </summary>
        internal static string tStaChkStk {
            get {
                return ResourceManager.GetString("tStaChkStk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Cash.
        /// </summary>
        internal static string tSumCash {
            get {
                return ResourceManager.GetString("tSumCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment summary(Currency).
        /// </summary>
        internal static string tSumCurrency {
            get {
                return ResourceManager.GetString("tSumCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Amt Drawer.
        /// </summary>
        internal static string tSumDrw {
            get {
                return ResourceManager.GetString("tSumDrw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string tSummary {
            get {
                return ResourceManager.GetString("tSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Redeem Point.
        /// </summary>
        internal static string tSumRedeem {
            get {
                return ResourceManager.GetString("tSumRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Amt Refund.
        /// </summary>
        internal static string tSumRet {
            get {
                return ResourceManager.GetString("tSumRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Amt Sales.
        /// </summary>
        internal static string tSumSale {
            get {
                return ResourceManager.GetString("tSumSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX ID.
        /// </summary>
        internal static string tTaxID {
            get {
                return ResourceManager.GetString("tTaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX INVOICE(ABB.).
        /// </summary>
        internal static string tTaxInvoice {
            get {
                return ResourceManager.GetString("tTaxInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You For Choosing Us.
        /// </summary>
        internal static string tThanks {
            get {
                return ResourceManager.GetString("tThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string tTicket {
            get {
                return ResourceManager.GetString("tTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit URL.
        /// </summary>
        internal static string tTitleEdit {
            get {
                return ResourceManager.GetString("tTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string tTitleURL {
            get {
                return ResourceManager.GetString("tTitleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-up.
        /// </summary>
        internal static string tTopup {
            get {
                return ResourceManager.GetString("tTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total new price.
        /// </summary>
        internal static string tTotalNewPri {
            get {
                return ResourceManager.GetString("tTotalNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total old price.
        /// </summary>
        internal static string tTotalOldPri {
            get {
                return ResourceManager.GetString("tTotalOldPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string tUnitName {
            get {
                return ResourceManager.GetString("tUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Point.
        /// </summary>
        internal static string tUsePnt {
            get {
                return ResourceManager.GetString("tUsePnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string tUsername {
            get {
                return ResourceManager.GetString("tUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string tUsr {
            get {
                return ResourceManager.GetString("tUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT EXCLUDED.
        /// </summary>
        internal static string tVatExcluded {
            get {
                return ResourceManager.GetString("tVatExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT INCLUDED.
        /// </summary>
        internal static string tVatIncluded {
            get {
                return ResourceManager.GetString("tVatIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string tWelcome {
            get {
                return ResourceManager.GetString("tWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Field.
        /// </summary>
        internal static string tWholeField {
            get {
                return ResourceManager.GetString("tWholeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband.
        /// </summary>
        internal static string tWristband {
            get {
                return ResourceManager.GetString("tWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband No. / Card No..
        /// </summary>
        internal static string tWristbandNo {
            get {
                return ResourceManager.GetString("tWristbandNo", resourceCulture);
            }
        }
    }
}
