//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2PSMaster.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCNTPdtTnfHD
    {
        public string FTBchCode { get; set; }
        public string FTXthDocNo { get; set; }
        public string FTShpCode { get; set; }
        public string FTXthTnfType { get; set; }
        public Nullable<int> FNXthDocType { get; set; }
        public Nullable<System.DateTime> FDXthDocDate { get; set; }
        public string FTXthVATInOrEx { get; set; }
        public string FTXthCshOrCrd { get; set; }
        public string FTXthOther { get; set; }
        public string FTDptCode { get; set; }
        public string FTXthBchFrm { get; set; }
        public string FTXthBchTo { get; set; }
        public string FTXthShopFrm { get; set; }
        public string FTXthShopTo { get; set; }
        public string FTXthWhFrm { get; set; }
        public string FTXthWhTo { get; set; }
        public string FTUsrCode { get; set; }
        public string FTSpnCode { get; set; }
        public string FTXthApvCode { get; set; }
        public string FTSplCode { get; set; }
        public string FTXthRefExt { get; set; }
        public Nullable<System.DateTime> FDXthRefExtDate { get; set; }
        public string FTXthRefInt { get; set; }
        public Nullable<System.DateTime> FDXthRefIntDate { get; set; }
        public Nullable<int> FNXthDocPrint { get; set; }
        public string FTRteCode { get; set; }
        public Nullable<decimal> FCXthRteFac { get; set; }
        public string FTVatCode { get; set; }
        public Nullable<decimal> FCXthVATRate { get; set; }
        public Nullable<decimal> FCXthTotal { get; set; }
        public Nullable<decimal> FCXtVatNoDisChg { get; set; }
        public Nullable<decimal> FCXthNoVatNoDisChg { get; set; }
        public Nullable<decimal> FCXthVatDisChgAvi { get; set; }
        public Nullable<decimal> FCXthNoVatDisChgAvi { get; set; }
        public string FTXthDisChgTxt { get; set; }
        public Nullable<decimal> FCXthDis { get; set; }
        public Nullable<decimal> FCXthChg { get; set; }
        public Nullable<decimal> FCXthRefAEAmt { get; set; }
        public Nullable<decimal> FCXthVatAfDisChg { get; set; }
        public Nullable<decimal> FCXthNoVatAfDisChg { get; set; }
        public Nullable<decimal> FCXthAfDisChgAE { get; set; }
        public string FTXthWpCode { get; set; }
        public Nullable<decimal> FCXthVat { get; set; }
        public Nullable<decimal> FCXthVatable { get; set; }
        public Nullable<decimal> FCXthGrandB4Wht { get; set; }
        public Nullable<decimal> FCXthWpTax { get; set; }
        public Nullable<decimal> FCXthGrand { get; set; }
        public Nullable<decimal> FCXthRnd { get; set; }
        public string FTXthGndText { get; set; }
        public Nullable<decimal> FCXthPaid { get; set; }
        public Nullable<decimal> FCXthLeft { get; set; }
        public string FTXthStaRefund { get; set; }
        public string FTXthRmk { get; set; }
        public string FTXthStaDoc { get; set; }
        public string FTXthStaApv { get; set; }
        public string FTXthStaPrcStk { get; set; }
        public string FTXthStaPaid { get; set; }
        public Nullable<int> FNXthStaDocAct { get; set; }
        public Nullable<int> FNXthStaRef { get; set; }
        public string FTRsnCode { get; set; }
        public Nullable<System.DateTime> FDLastUpdOn { get; set; }
        public string FTLastUpdBy { get; set; }
        public Nullable<System.DateTime> FDCreateOn { get; set; }
        public string FTCreateBy { get; set; }
    }
}
