//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2PSMaster.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCNTPdtTnfDTSrn
    {
        public string FTBchCode { get; set; }
        public string FTXthDocNo { get; set; }
        public long FNXtdSeqNo { get; set; }
        public string FTPdtCode { get; set; }
        public string FTSrnCode { get; set; }
        public Nullable<System.DateTime> FDXtdSDate { get; set; }
        public Nullable<decimal> FCPtsCost { get; set; }
    }
}
