//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2PSMaster.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCNTPdtTnfHDRef
    {
        public string FTBchCode { get; set; }
        public string FTXthDocNo { get; set; }
        public string FTXphDstPaid { get; set; }
        public Nullable<int> FNXphCrTerm { get; set; }
        public Nullable<System.DateTime> FDXphDueDate { get; set; }
        public Nullable<System.DateTime> FDXphBillDue { get; set; }
        public string FTXphCtrName { get; set; }
        public Nullable<System.DateTime> FDXphTnfDate { get; set; }
        public string FTXphRefTnfID { get; set; }
        public string FTXphRefVehID { get; set; }
        public string FTXphRefInvNo { get; set; }
        public string FTXphQtyAndTypeUnit { get; set; }
        public Nullable<long> FNXphShipAdd { get; set; }
        public Nullable<long> FNXphTaxAdd { get; set; }
        public string FTViaCode { get; set; }
    }
}
