//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2PSMaster.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCNTPdtTnfDT
    {
        public string FTBchCode { get; set; }
        public string FTXthDocNo { get; set; }
        public int FNXtdSeqNo { get; set; }
        public string FTPdtCode { get; set; }
        public string FTXtdPdtName { get; set; }
        public string FTXtdStkCode { get; set; }
        public Nullable<decimal> FCXtdStkFac { get; set; }
        public string FTPunCode { get; set; }
        public string FTPunName { get; set; }
        public Nullable<decimal> FCXtdFactor { get; set; }
        public string FTXtdBarCode { get; set; }
        public string FTXtdVatType { get; set; }
        public string FTVatCode { get; set; }
        public Nullable<decimal> FCXtdVatRate { get; set; }
        public string FTXtdSaleType { get; set; }
        public Nullable<decimal> FCXtdSalePrice { get; set; }
        public Nullable<decimal> FCXtdQty { get; set; }
        public Nullable<int> FCXtdQtyAll { get; set; }
        public Nullable<decimal> FCXtdSetPrice { get; set; }
        public Nullable<decimal> FCXtdAmt { get; set; }
        public Nullable<decimal> FCXtdDisChgAvi { get; set; }
        public string FTXtdDisChgTxt { get; set; }
        public Nullable<decimal> FCXtdDis { get; set; }
        public Nullable<decimal> FCXtdChg { get; set; }
        public Nullable<decimal> FCXtdNet { get; set; }
        public Nullable<decimal> FCXtdNetAfHD { get; set; }
        public Nullable<decimal> FCXtdNetEx { get; set; }
        public Nullable<decimal> FCXtdVat { get; set; }
        public Nullable<decimal> FCXtdVatable { get; set; }
        public Nullable<decimal> FCXtdWhtAmt { get; set; }
        public string FTXtdWhtCode { get; set; }
        public Nullable<decimal> FCXtdWhtRate { get; set; }
        public Nullable<decimal> FCXtdCostIn { get; set; }
        public Nullable<decimal> FCXtdCostEx { get; set; }
        public string FTXtdStaPdt { get; set; }
        public Nullable<decimal> FCXtdQtyLef { get; set; }
        public Nullable<decimal> FCXtdQtyRfn { get; set; }
        public string FTXtdStaPrcStk { get; set; }
        public string FTXtdStaAlwDis { get; set; }
        public Nullable<int> FNXtdPdtLevel { get; set; }
        public string FTXtdPdtParent { get; set; }
        public Nullable<decimal> FCXtdQtySet { get; set; }
        public string FTXtdPdtStaSet { get; set; }
        public string FTXtdRmk { get; set; }
        public Nullable<System.DateTime> FDLastUpdOn { get; set; }
        public string FTLastUpdBy { get; set; }
        public Nullable<System.DateTime> FDCreateOn { get; set; }
        public string FTCreateBy { get; set; }
    }
}
